version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: lms_redis
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redisdata:
